### ISSUE TITLE
Hook Packagist

### ISSUE THREAD

**Issue by ProPheT777** [mcordingley/PHPStats#30]
Packagist hook is not activated, so your tags are not available through composer.

**Comment by mcordingley** [comment]
Hi ProPheT777. This project is no longer maintained. I would strongly urge those with an interest in the code to roll their own solutions, borrowing code from here as needed. It's my opinion that this package is too large and unfocused for modern PHP and that new packages would benefit from being focused on subsets of what this originally set out to do.
